### ISSUE TITLE
[ERROR] migration '20210206_drop_badges_column_add_sharing_flags' failed

### ISSUE THREAD

**Issue by YC** [muety/wakapi#128]
```
2021-02-16T02:33:58.628088167Z [INFO ] potentially running migration '20210206_drop_badges_column_add_sharing_flags'
2021-02-16T02:33:58.701952316Z [ERROR] migration '20210206_drop_badges_column_add_sharing_flags' failed – table users already exists
panic: migration '20210206_drop_badges_column_add_sharing_flags' failed – table users already exists

goroutine 1 [running]:
github.com/emvi/logbuch.(*StandardFormatter).Pnc(0xc00000e060, 0xcf51c2, 0x1c, 0xc00117d940, 0x2, 0x2)
	/go/pkg/mod/github.com/emvi/logbuch@v1.1.1/standard_formatter.go:59 +0x8e
github.com/emvi/logbuch.(*Logger).Fatal(0xc00010c000, 0xcf51c2, 0x1c, 0xc00117d940, 0x2, 0x2)
	/go/pkg/mod/github.com/emvi/logbuch@v1.1.1/logger.go:132 +0xb3
github.com/emvi/logbuch.Fatal(...)
	/go/pkg/mod/github.com/emvi/logbuch@v1.1.1/funcs.go:55
github.com/muety/wakapi/migrations.RunCustomPostMigrations(0xc0010d84b0, 0xc00012c9a0)
	/src/migrations/migrations.go:52 +0x24a
main.main()
	/src/main.go:122 +0x3aa
0
```

```
sqlite> .schema users
CREATE TABLE users
(
    id       varchar(255) primary key,
    api_key  varchar(255) unique,
    password varchar(255)
, `created_at` timestamp default '2020-01-01T00:00:00.000' not null, `last_logged_in_at` timestamp default '2020-01-01T00:00:00.000' not null, `badges_enabled` tinyint(1) default 0 not null, `wakatime_api_key` text, `share_oss` numeric DEFAULT false, `has_data` numeric DEFAULT false, `is_admin` numeric DEFAULT false, `share_data_max_days` integer DEFAULT 0, `share_languages` numeric DEFAULT false, `share_editors` numeric DEFAULT false, `share_projects` numeric DEFAULT false, `share_machines` numeric DEFAULT false);
```

Version: latest/1.24.1 on Docker Hub

**Comment by muety** [comment]
Thanks for the bug report. I found the problem. I (again) forgot to take into account that SQLite [doesn't allow to rename or drop columns](https://stackoverflow.com/a/8442173/3112139). 

The fix here would be to include a check like [this](https://github.com/muety/wakapi/blob/759e8e4dfdba92de14d996f711f9b4df40722278/migrations/20210202_fix_cascade_for_alias_user_constraint.go#L18) before attempting to [drop the column](https://github.com/muety/wakapi/blob/759e8e4dfdba92de14d996f711f9b4df40722278/migrations/20210206_drop_badges_column_add_sharing_flags.go#L40) and, in case SQLite is used, skip the drop statement and just keep the column. Also, since that "isSqlite"-like check is used several times in the migrations funcs, it would probably make sense to outsource it to a static util function. 

You're welcome to take a look into this fix, otherwise I'll give it a shot tonight.

Honestly, I'd like to drop support for SQLite, because (1) its lack of certain functionality keeps bringing up issues over and over again and (2) we wouldn't depend on C code (and gcc, etc.) then, but have a pure Go program. However, I'd also like to have Wakapi setup as easy as possible and that includes not having to stand up a whole database server.

**Comment by YC** [comment]
Hopefully the check is in the right place. 
My memory is a little fuzzy on my initial configuration (with docker-compose), but if I did indeed switch from the default, the reason is probably to avoid running database server containers due to limited resources.

**Comment by muety** [comment]
Default is SQLite, because setup is easy and performance is more than sufficient for single-user self-hosted instances. I'll keep SQLite as the default for those reasons, although I don't quite like it.
