### ISSUE TITLE
Can't disable signup

### ISSUE THREAD

**Issue by dashezup** [muety/wakapi#185]
I have `allow_signup` set to false in my `config.yml`, but it still allows me to sign up new accounts. I'm using docker image (latest, tag `1.26.5`), I've also tried to recreate the volume but still.

```
security:
    allow_signup: false
```

I'm running it with production mode beside a reverse proxy with a subpath of URL.

And an extra question, I saw that the first account which created was admin, can differentiate them from the web ui? or there isn't anything special with admin account for usage for now?

**Comment by muety** [comment]
> I have `allow_signup` set to false in my `config.yml`, but it still allows me to sign up new accounts. I'm using docker image (latest, tag `1.26.5`), I've also tried to recreate the volume but still.

I think I know what the problem is. The Dockerfile defines `ENV WAKAPI_ALLOW_SIGNUP 'true'` so you can create your initial user and as environment variables take precedence over the config file, your settings option get overriden. Try to start your container with `-e "WAKAPI_ALLOW_SIGNUP=false"` and let me know if it solved your issue.

> And an extra question, I saw that the first account which created was admin, can differentiate them from the web ui? or there isn't anything special with admin account for usage for now?

As you figured correctly, the first user created is by default an admin and currently the only way to change that is through manually modifying the database entry. The only place where an _admin_ account his higher privileges over any other user is the `/metrics` endpoint. When calling it as an ordinary user, you will only see your personal stats, however, an admin will additionally see global, server-wide metrics.

**Comment by dashezup** [comment]
> I think I know what the problem is. The Dockerfile defines `ENV WAKAPI_ALLOW_SIGNUP 'true'` so you can create your initial user. As environment variables take precedence over the config file, your settings option gets overwritten

Yes, solved by adding environment section in my `docker-compose.yml`

```
    wakapi:
        environment:
            - WAKAPI_LISTEN_IPV4=wakapi
            - WAKAPI_INSECURE_COOKIES=false
            - WAKAPI_ALLOW_SIGNUP=false
```

This also cleared up my confusion about the ipv4 listening address always being `0.0.0.0`, it's also overwritten by the environment variable.

https://github.com/muety/wakapi/blob/6256c8e10a3ab5c2c53bbe6a26f433b5c6503c12/Dockerfile#L34-L44

**Comment by fuzunspm** [comment]
I created my user and then disabled signup withing docker-compose but after the command `docker-compose up -d` it still lets users signup. I think i'm missing something here.

**Comment by muety** [comment]
Did you modify `config.yml` in any way? What other environment variables are you passing along? And did you recreate the container after your initial signup?

**Comment by fuzunspm** [comment]
Yes i modified config.default.yml file but it's set to false now. I passed postgres and email config variables. Others are default. How should i re create the container? with --force-recreate ?

**Comment by muety** [comment]
What did you set as `env` (`ENVIRONMENT`). Any yes, please try with `--force-recreate`.

**Comment by fuzunspm** [comment]
ENVIRONMENT: prod. I tried --force-recreate but signup button still shows up

**Comment by muety** [comment]
Yeah, the signup button won't disappear, but when trying to perform the signup you'll get an error instead.

**Comment by fuzunspm** [comment]
I'm sorry, I wasted your time.

**Comment by muety** [comment]
No worries. I see that it's a bit confusing that the registration form still appears although signup is disabled.
