### ISSUE TITLE
Why is the project name obfuscation set invalid?

### ISSUE THREAD

**Issue by jeffxjh** [muety/wakapi#201]
.wakatime.cfg :
[settings]
hide_file_names = true
hide_project_names = true

**Comment by muety** [comment]
Hi, can you please specify the problem a bit further? What exactly is going wrong?

**Comment by jeffxjh** [comment]
Thank you for reply,I deployed Wakapi using Docker, I used Idea,setting the wakatime.cfg "hide_project_names = true",but it look like not working. i delete the sqllite.db,reopen idea ,continue coding ,still not working.

**Comment by jeffxjh** [comment]
> Hi, can you please specify the problem a bit further? What exactly is going wrong?

Thank you for reply,I deployed Wakapi using Docker, I used Idea,setting the wakatime.cfg "hide_project_names = true",but it look like not working. i delete the sqllite.db,reopen idea ,continue coding ,still not working.

**Comment by muety** [comment]
I believe by "not working" you mean that project names are not obfuscated, but still sent as they are? If that's the case, then this seems to be an issue with _wakatime-cli_ rather than Wakapi.

Do you have anything defined under `[projectmap]`? In my recent tests, any project defined there will not be obfuscated. Also, what wakatime version are you using (`~/.wakatime/wakatime-cli/wakatime-cli --version`)?

**Comment by muety** [comment]
Your settings seem to be alright. Maybe try to open an issue in the official [wakatime](https://github.com/wakatime/wakatime) repo?

**Comment by jeffxjh** [comment]
maybe is proxy problem,think for answer!
