### ISSUE TITLE
Project labels not respecting aliases

### ISSUE THREAD

**Issue by muety** [muety/wakapi#231]
When summarizing projects _A_ and _B_ under an alias _AB_, a user will only ever see _AB_ in her statistics. To create a new project label, a user would in fact have to create new labels for all projects included in that alias. This is cumbersome and not intuitive. Instead, aliases should be respected when computing project label statistics.

**Comment by andrenasturas** [comment]
Actually, it does not even works. Aliased projects falls into the `default` label.

### Reproduction

Given a project `A`, do the following in any order :
- Create an alias renaming `A` to `B`.
- Create a label tagging `A` as `label`.

Observe that the Labels chart indicates a `default` part for the project `A`. Remove the alias and that part became, as expected, a `label` part.

(Tested on `v1.30.3@postgres` on ArchLinux)

I did not inspect the code yet, but I obviously suspect that at the moment the Labels chart is produced, it checks the existing labels for each projects, but the projects are already substituted by their respective aliases.

### Expected behavior

In the Project Label settings sections, the project list should list the projects after alias substitution.

**Comment by muety** [comment]
Thanks for the detailed explanation. I'll get to fix this hopefully very soon.

**Comment by muety** [comment]
I thought about this again. I think for the scenario you described, the behavior is actually not so wrong. If you remap `A` to `B`, then `A` appears to just be not existing anymore, so I think it's fine for any labels of `A` to have no effect. You're saying "_`A` is `B` now_", so if you want to label it, you will need to label `B`.

Would you agree?

The only thing that's confusing then is `A` to still show up in the project selection on the settings page.

**Comment by andrenasturas** [comment]
> You're saying "*`A` is `B` now*", so if you want to label it, you will need to label `B`.

I agree. The problem was that it was not possible to label `B`.

> Of course, what we could do is "inherit" all labels of the source project to the target project.

That would be useful in the case `A` is labelled, and then remapped later to `B`, leaving the `A` labeling broken otherwise ? But I suppose this is a very limited use case.

(Unrelated, but wakapi has just been updated on AUR. Nice job with the new UI, i like it ! :slightly_smiling_face:)
