### ISSUE TITLE
Support wakatime-chrome extension

### ISSUE THREAD

**Issue by shyn** [muety/wakapi#237]
Installed chrome extension from wakatime.com. It's seems like I can't set the api endpoint. So the only way is the clone the source code and replace wakatime api with wakapi?

Searched issues found nothing about this.

**Comment by YC** [comment]
![Screenshot_2021-08-30_13-39-33](https://user-images.githubusercontent.com/5828744/131281881-d438e01c-ecbd-4e9f-8a74-1a9e4912f250.png)
I think you're right. 
It doesn't seem to be adjustable.

**Comment by muety** [comment]
Very unfortunate! I opened https://github.com/wakatime/chrome-wakatime/issues/130 in the upstream repo, let's see if some solution can be found. @shyn, are you using wakapi.dev or a self-hosted instance?

**Comment by shyn** [comment]
> Very unfortunate! I opened [wakatime/chrome-wakatime#130](https://github.com/wakatime/chrome-wakatime/issues/130) in the upstream repo, let's see if some solution can be found. @shyn, are you using wakapi.dev or a self-hosted instance?

I use a  self-hosted instance.
Appreciate the upstream issue. I will watch it, thx!

**Comment by gaocegege** [comment]
I ran the chrome extension successfully, but we cannot get the correct os/editor/machine because of the user-agent. The user-agent from the browser looks like `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36`

wakapi cannot parse it.

**Comment by muety** [comment]
Thanks for investigating! I'll have a look at the user agent issue soon.

**Comment by gaocegege** [comment]
Thanks! We can maintain a chrome-wakatime fork to support wakapi.dev. But it is hard to keep one extension for all self-hosted instances. We need to work around ajax/chrome extension CORS problems.

**Comment by muety** [comment]
Okay, so here's the plan:

* [x] Fork the official plugin
* [ ] https://github.com/muety/chrome-wakapi/issues/1
* [ ] https://github.com/muety/chrome-wakapi/issues/2
* [ ] https://github.com/muety/chrome-wakapi/issues/3
* [ ] Publish `chrome-wakapi` plugin to Chrome- and Firefox stores
* [ ] Add usage instructions to README

Right now, this is blocked by https://github.com/wakatime/chrome-wakatime/issues/135. Unfortunately, I can't properly build the plugin, so I can't continue with the above points. Maybe it's only me, but otherwise we'll have to wait for someone to fix the plugin build.

Also, **help is highly appreciated** here, especially because the plugin is written in React, which I don't have any expertise with.

**Comment by muety** [comment]
Sorry, I don't want to pressure you. If you think you can't afford time for this more or less soon-ish then I'll have a look. However, it's probably gonna take me much longer, as I'm not familiar with React, etc.

**Comment by f97** [comment]
I just found wakapi but I am very love it and I am intending to support this task but I found this extension uses manifest v2. I don't know if wakatime has any plans to move to v3 version?🤪🤪

**Comment by f97** [comment]
I am developing a small extension, I hope I will release it soon.

![image](https://user-images.githubusercontent.com/35532964/159606524-4d422161-54cc-4afb-8cde-f70dc2833a22.png)

**Comment by muety** [comment]
@f97 How is going forward with your extension? Is there anything we can help you with?

**Comment by f97** [comment]
@muety  
hehe, I've had a lot of problems with my life, work, and love lately, so I can't make time for the promise of writing this extension. 

I have a bit of free time these days so I quickly code a small extension, but I'm having a problem that I don't know what to push. 

I tried a few things but still not satisfied, you can contribute [here](https://github.com/f97/chrome-wakapi.git).

At least it works but it doesn't work properly: 3

https://github.com/f97/chrome-wakapi.git 

![image](https://user-images.githubusercontent.com/35532964/178630064-d8ba58fa-4a28-4f66-9186-2bdcabbff958.png)

**Comment by muety** [comment]
That is great news! I'm excited to check out what you already came up with. Maybe you can add a brief list of things that would still need to be done / are not working yet - e.g. in the form of issues or as part of your project's README - and I'm sure people will be happy to jump in and contribute to get this thing live! 🚀

And of course, don't feel obliged here by any means! Get your private stuff sorted and only spend time on coding this if you actually feel like so.

**Comment by alexanderadam** [comment]
I like the relay idea.
Just to throw another idea into the room:

if the wakapi host would be provided (i.e. `WAKAPI_API_URL`), then wakapi could build the extensions on Docker boot (_maybe some `npm build` resulting in an URL dependent file name, so that it won't be rebundled if the hostname or the file hashes didn't change_) and put them into the asset directory.

Of course this would mean, that a new wakapi container image must be pulled to get the updated extension but on the other hand this would also make sure that the API always matches.

And I think there's an extra warning when installing extensions from other hosts.

But other than that it would be nice because users know that they don't have to send their activities via a third party.

I'm not

**Comment by muety** [comment]
I'll ahve a look into [content scripts](https://developer.chrome.com/docs/extensions/mv3/content_scripts/#dynamic-declarative) to see if that could help us by any means. Thanks for the pointer. 

Apart from that, if I got your solution approach (building the extension with custom API URL at container build- / run time) correctly, it would mean that everyone, who is self-hosting Wakapi, would have to build and install their own browser extension, no? Of course, this is always an option. But I'd like to have a solution where people can just go to the Chrome / Firefox store and install an official add-on right from the marketplace.

However, the main blocker on this ticket is anyways the extension itself, which would require a few adaptions, but whose code unfortunately seems to be abandoned. 

Again, if anyone has good expertise with (a) React and (b) the WebExt API, help is highly appreciated here! 🙂

**Comment by qhantom** [comment]
> [wakatime/chrome-wakatime#135](https://github.com/wakatime/chrome-wakatime/issues/135) finally got resolved in the upstream repo, so no more blockers for us! 🙌
> 
> Next steps: as described [above](https://github.com/muety/wakapi/issues/237#issuecomment-942390440).
> 
> I'd be super thankful if someone with a bit of React experience could help out in this! @qhantom, maybe? 😇

Sure, gonna have a look at https://github.com/muety/chrome-wakapi/issues/2 :-)

**Comment by varac** [comment]
@muety I also got the official chrome-wakatime plugin compiled and successfully installed, after I changed the URL in the source to my wakapi server.
In the inspector window I see requests beeing sent to my server on every new website I visit:

![image](https://user-images.githubusercontent.com/488213/224576729-aa75a486-8373-4fd0-8651-d0759ed470de.png)

my Wakapi server recieves the requests:

    2023-03-12T22:12:28.00305202Z [INFO ] [request] status=201, method=POST, uri=/api/v1/users/current/heartb
eats?api_key=..., duration=42.284249ms, bytes=27, addr=x.x.x.x, user
=varac 

But I don't see anything in my dashboard (besides  my NeoVim plugin entries).
How can I debug further, or has Wakapi still issues with parsing the useragent payload entry as mentioned above (https://github.com/muety/wakapi/issues/237#issuecomment-939427621) ? 

I also don't see any domains showing up in the Dashboard. 
Any help appreciated on how to get the chrome-wakatime plugin working before any of the plugins support custom URLs from UI.

**Comment by muety** [comment]
Hi @varac, thanks for reporting this!

To clarify, you don't see your coding time reflected in the Wakapi dashboard at all or is it just classified as _unknown_? Also, do you see any error messages in the server's logs?

The user agent issue from above most likely still persists. I'll look into it soon!

**Comment by muety** [comment]
I fixed parsing the user agent strings, so you should see "Chrome" appearing as an editor now.

However, I realized that domains / web pages are implemented as entities (aka. files), while Wakapi currently [does not support file statistics](https://github.com/muety/wakapi/issues/80#issuecomment-993709940) at the moment. I'll have to reconsider this, because otherwise, the browser plugin would be rather useless.

**Comment by varac** [comment]
Great! As soon as there's a new image tag I'll test and can give feedback. Thanks!

**Comment by muety** [comment]
[browser-wakatime](https://github.com/wakatime/browser-wakatime) now supports sending data to Wakapi. See [instructions here](https://github.com/muety/wakapi#browser-plugin-chrome--firefox). :heavy_check_mark:
