### ISSUE TITLE
Make cookies respect `base_path`

### ISSUE THREAD

**Issue by jabra98** [muety/wakapi#310]
Hi, I do actually self-host two versions of Wakapi. One is at tag 1.30.3 and the other one is at 2.0.1. They are setup so that my client sends the heartbeats to 1.30.3 at port 3000 and that version relays to the other version (2.0.1) at port 3001 (with minor modifications to the relay logic, so that it accepts anything other than WakaTime). 2.0.1 in turn relays to WakaTime. It works flawlessly so far but I noticed that when I log-in into the web interface of one version, I'm being kicked out from the other one immediately (when refreshing the page). I suppose it has something to do with how the log-in/session cookie is handled. Any idea what would cause this behavior? 

edit: Here is a clip showcasing this: https://www.youtube.com/watch?v=vVk22gp8bNs

**Comment by muety** [comment]
Very interesting question. The behavior you described happens due to the fact that you're running both instances under the same domain. Cookies are set globally for a domain, so a cookie for instance 1 will well be sent to instance 2 as well. Since cookies contain an instance-specific signature, they are not accepted mutually.

We might actually be able to "fix" this, by including the  `base_path` config variable to the cookie's path. I'll do a few experiments these days.

In the mean time, easiest thing that you could do is is run both instances under different subdomains.

**Comment by muety** [comment]
Why are you running two parallel instances on different version in the first place, though?

**Comment by jabra98** [comment]
Oh, I see. Uh I don’t have a particular good reason for this setup. I just wanted one version to consist only of its own heartbeats, whereas the other one merged with thise imported from WakaTime.

**Comment by muety** [comment]
I did some changes to the cookie creation logic. If you have time, please test if that works for you.

**Comment by jabra98** [comment]
Looks good, thanks!
