### ISSUE TITLE
Feature request: Add label to many projects at once

### ISSUE THREAD

**Issue by notarock** [muety/wakapi#368]
I really like the project label feature, and I use it quite a bit:

![image](https://user-images.githubusercontent.com/25652765/166954035-3f136cdc-70af-470f-ac70-7e4fbb9af9fe.png)

I recently started working at a new company, which means working with more than 25+ new repositories within the last months. I want to label these projects as "Company" but doing so one-by-one is quite tedious.

Simple QOL request, it would be awesome if we could do something like:

![wakapi-projects-picker](https://user-images.githubusercontent.com/25652765/166955462-ffbf9812-3c53-4947-84f4-3071aba2df78.png)

That way, you can do it once instead of picking Project / Label and hitting save 25 times

**Comment by muety** [comment]
Thanks, I see how this will be beneficial. I'll add it as a feature request with not-so-high prio.

**Comment by IgnisDa** [comment]
Hello @muety I would like to work on this.

**Comment by IgnisDa** [comment]
This is what I came up with

![Untitled-2023-01-24-0716](https://user-images.githubusercontent.com/60938164/214197789-4e91c53d-2269-4571-ab58-3ca15296d293.png)

**Comment by IgnisDa** [comment]
So as far as I can see, every time a new label is added in the current UI, a new `ProjectLabel` model is created associated with the `ProjectKey`. In which case the above UI might not be possible.

Correct me if I am wrong, but there does not seem to be any existing model that stores projects explicitly. They are just stored as `string` in the `heartbeat` model.

**Comment by muety** [comment]
Hi @IgnisDa, thanks a lot for these very elaborate thoughts! I really like the concept you came up with. Feel free to give it a go! 

To give you a couple of hints as a guideline (without having fully thought through this): you'll probably have to adapt the [`adtionAddLabel()`](https://github.com/muety/wakapi/blob/749782b15b7cc7721a0a57e44ca8dd4f016ccacc/routes/settings.go#L361-L383) handlers (sorry, the `settings.go` is pretty messy, I have a to-do on my list to split the settings up into separate pages) to accept an array of values for `key` and `value`, instead of only a single one. See [here](https://stackoverflow.com/questions/28699582/how-get-multiselect-values-from-form-using-golang/28700234#28700234) (and potentially [here](https://stackoverflow.com/questions/34313657/html-form-post-an-array-of-objects/34753224#34753224)). Try to use as little JavaScript as possible, but of course as much as needed. 

> Correct me if I am wrong, but there does not seem to be any existing model that stores projects explicitly. They are just stored as string in the heartbeat model.

Yep, that's right, projects are simply identified by their plain name strings (same for languages, editors, etc.).

**Comment by IgnisDa** [comment]
Will work on this.

Can you tell me the normal development workflow you follow? I run `go run . -- --config config.yml` in the project root. When I make a change to the go code, I have to restart the server and have to login again in the browser. Is there a way to circumvent this?

**Comment by muety** [comment]
Yes, exactly. That's my current development workflow. If you wanted to circumvent having to re-login each time, you could probably set the securecookie's secrets to some constant string, instead of a random value.

**Comment by IgnisDa** [comment]
Can you tell me which setting in this table? https://github.com/muety/wakapi#-configuration-options

**Comment by muety** [comment]
There's no setting for that, you'd have to do it in code [here](https://github.com/muety/wakapi/blob/master/config/config.go#L398-L402). But I always just re-logged in every time again.

**Comment by IgnisDa** [comment]
Would be useful for development if we make that configurable via an env variable.

**Comment by muety** [comment]
Agree! Created #463 for this.
