### ISSUE TITLE
Provide arm64 releases

### ISSUE THREAD

**Issue by muety** [muety/wakapi#401]
Currently, we're building x64 binaries for Linux, Windows and Mac. Especially now, that ARM-based machines gain in popularity (Mac M1, AWS Graviton2, ...) we should also provide builds for arm64 architecture. This is also a prerequisite for #400.

Easiest would probably be to add an `arch` dimension to our build matrix, see https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context. 

Alternatively, we could consider switching to https://github.com/goreleaser/goreleaser-action (inspired by https://github.com/screego/server/blob/master/.github/workflows/build.yml), but I don't know if that's worth the effort. 

@YC Would you mind taking a look into this, as you're way more familiar with GHA than I am?

**Comment by YC** [comment]
Unfortunately, there's no one-liner solution, since there're no Github hosted runners which run on arm64. 
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

The 2 alternate solutions that I can think of is cross-compilation and cross-compilation through Docker. 
Will investigate.

**Comment by muety** [comment]
Very unfortunate, but good to know. Thanks for your research! Keep me posted :)

**Comment by YC** [comment]
The `GOOS` and `GOARCH` solution is probably worth a try. 
https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63
