### ISSUE TITLE
SQLite stopped working

### ISSUE THREAD

**Issue by NickAcPT** [muety/wakapi#403]
**Describe the bug**
I upgraded from a previous  version (I don't remember which one exactly) and SQLite doesn't work anymore.

```
2022-09-07T00:25:24.736313+01:00 [WARN ] with sqlite, only a single connection is supported
2022-09-07T00:25:24.7368331+01:00 [ERROR] Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
2022-09-07T00:25:24.7368331+01:00 [ERROR] could not open database
panic: could not open database

goroutine 1 [running]:
github.com/emvi/logbuch.(*StandardFormatter).Pnc(0xc0000da000?, {0xde9718?, 0xde9718?}, {0x0?, 0x0?, 0x0?})
        /home/runner/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/standard_formatter.go:57 +0x3f
github.com/emvi/logbuch.(*Logger).Fatal(0xc0000da000, {0xde9718, 0x17}, {0x0, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/logger.go:132 +0x77
github.com/emvi/logbuch.Fatal(...)
        /home/runner/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/funcs.go:55
main.main()
        /home/runner/work/wakapi/wakapi/main.go:126 +0x379
```

**System information**
Please provide information on:
* Wakapi version 2.3.8 (amd64)
* Operating system Windows 11
* Database (SQLite, MySQL, ... ?) SQLite

**Comment by muety** [comment]
Sorry for the inconveniences! May I ask how you are running Wakapi? From a GitHub release binary / self-compiled / with `go install` / in Docker?

**Comment by NickAcPT** [comment]
> Sorry for the inconveniences! May I ask how you are running Wakapi? From a GitHub release binary / self-compiled / with `go install` / in Docker?

@muety sorry for not mentioning it, I downloaded it directly from the 2.3.8 release here on GitHub

**Comment by muety** [comment]
Thanks, I could reproduce the issue on my Windows machine. Even worse, Windows defender kicks in and just deletes the EXE for me.

This error is due to the latest changes in #402. Before, Windows binaries were compiled on Windows, now we attempted to do cross-compilation from Linux. Apparently, cross-compilation for Win is a bit harder when your program depends on cgo, see https://stackoverflow.com/a/41572593. You'll need MinGW, which kind of makes sense.

We'll have to revisit the release workflow again. I see two options. First option is trying to get cross-compilation with MinGW to work (as described in that post above). Second option is to compile for Mac and Linux on Linux and use Windows runners (as before) to compile the Windows binary. The second approach is probably easier, but comes with the downside that we can't compile arm64 EXEs then (see #401). But I think that would be acceptable, since ARM-based computers with Windows are probably anyway a very rare combination. Plus, I'm not sure if you can compile arm64 with MinGW on amd64. So I'd probably go for option 2, unless there is a third, even better option. Could you have another look at this, @YC? No rush though!

@NickAcPT I'll upload a fixed Windows EXE that I manually compiled on my local machine (using _tdm-gcc_, as escribed [here](https://github.com/mattn/go-sqlite3/issues/214#issuecomment-253216476)) as a quick fix, so you can keep going. ll

**Comment by YC** [comment]
Apologies, didn't anticipate this.  
I'll look into https://github.com/mattn/go-sqlite3/blob/master/README.md#compilation and perform a few tests.

**Comment by YC** [comment]
@muety Can you please delete all the arm64 releases?

```
$ file wakapi
wakapi: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=rt5oL3Dg5LrG_4H9LbSO/CxS-DGdQvYTZEM2fJCLz/V5xQ_5TmTdAMoYrAvcJP/nGHL8WvqdH8dWuQO0NE2, with debug_info, not stripped

$ ./wakapi
2022-09-07T07:45:50.005705269Z [WARN ] with sqlite, only a single connection is supported
2022-09-07T07:45:50.008835599Z [ERROR] Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
2022-09-07T07:45:50.008855279Z [ERROR] could not open database
```

**Comment by muety** [comment]
> Can you please delete all the arm64 releases?

Also the ones for Mac and Linux?

**Comment by YC** [comment]
I've deleted the arm64 zips. 
It's likely that darwin amd64 is also broken.
