### ISSUE TITLE
Implement `cummulative_total` key for WakaTime summaries endpoint

### ISSUE THREAD

**Issue by Koalhack** [muety/wakapi#426]
## Problem
Wakapi [#summaries](https://wakapi.dev/api/compat/wakatime/v1/users/current/summaries) doesn't respond with the "cummulative_total" key and value like Wakatime API [#summaries](https://wakatime.com/developers#summaries).

## Why
Which is a shame because by adding this value key we could easily integrate Wakapi with [Oh My Posh](https://ohmyposh.dev) Wakatime [Segment](https://ohmyposh.dev/docs/segments/wakatime)

**Comment by muety** [comment]
Hi @Koalhack, thanks for bringing this up! I think to correct endpoint to be used should be [`/statusbar](https://wakatime.com/developers#status_bar), as that's also the one used by `wakatime-cli --today` and, therefore, by all IDE plugins.

But since we can't easily change that and since the summaries endpoint is meant to be (mostly) compatible with WakaTime, I agree that we should implement that missing key as well!

I'm only trying to understand how `cummulative_total` is different from `data[].grand_total`. Could you perhaps do me a favor and post a data sample?

**Comment by muety** [comment]
Example response from WakaTime's summary endpoint: https://notebin.de/?fc4a86ad941e30de#BRWoJweke2aiKU5nb1g5ySxuQZ6ZJ8UGcLPx2YFiWYbH
