### ISSUE TITLE
Browser addon support seems has issue

### ISSUE THREAD

**Issue by SettingDust** [muety/wakapi#486]
**Describe the bug**
There isn't content in unknown project. But the time is recorded
![图片](https://github.com/muety/wakapi/assets/19922286/51e26312-d9c2-49f6-8aee-b92a0232af0d)
![图片](https://github.com/muety/wakapi/assets/19922286/b9b3c9fa-95c6-4de6-be7a-4498f6dfb9f0)

How is it show in wakatime
![图片](https://github.com/muety/wakapi/assets/19922286/50cfda17-3fc2-4d14-8a09-020e8fb308ab)

**System information**
Please provide information on:
* Wakapi version: docker latest tag. Should be 2.7.0 that I've tried pull and up to date
    * If Docker: which image and tag? https://github.com/muety/wakapi/pkgs/container/wakapi
* Database (SQLite, MySQL, ... ?) postgres:12.3

**Comment by muety** [comment]
Hi @SettingDust, thanks for reporting this. Unfortunately, I can't really reproduce this. Seems to be working for me:

![image](https://github.com/muety/wakapi/assets/8978843/3e09d312-f17f-4f2b-842d-aff3ebd675de)

Can you tell which version of the browser plugin you are using and potentially even show your config (with API key redacted)?

**Comment by SettingDust** [comment]
Firefox. Addon 3.0.12. 
![图片](https://github.com/muety/wakapi/assets/19922286/7dd9305f-0fc3-4fc1-8ecd-6f8dd0be3b0c)
![图片](https://github.com/muety/wakapi/assets/19922286/fe55f06f-a424-4e16-85cf-7bb732095185)

**Comment by SettingDust** [comment]
And there is an error
![图片](https://github.com/muety/wakapi/assets/19922286/7c3beb4b-8c50-4dbc-8595-26351fb34c46)

**Comment by SettingDust** [comment]
MB. After look into the addon console. Caused by CORS. Seems the addon haven't grant the permission for the host. Should be reported to addon repo

**Comment by muety** [comment]
The original WakaTime browser add-on does only have permissions for `wakatime.com`. The issue was discussed in https://github.com/muety/wakapi/issues/237, as a result of which we developed [chrome-wakapi](https://github.com/muety/chrome-wakapi) which (a) also has permissions for `wakapi.dev` and (b) allows to relay heartbeats to any other host (e.g. `wakapi.example.org`) through the official Wakapi instance, so no additional host permission are required for self-hosted instances.

However, since of course only works for publicly accessible instance, you won't be able to reach `localhost` this way. If you want the add-on to send data to `localhost`, there's no way around building the plugin yourself with custom host permissions compiled in.

> But why is there time recorded

Could be coincidence? Are you using Wakapi with any other plugins (e.g. VSCode, IntelliJ, etc.)? If yes, probably one of them has sent heartbeats for "unknown" project.

**Comment by SettingDust** [comment]
Well. Grant permission should be a feature for the addon

**Comment by muety** [comment]
Permissions must be defined at compile time via [`host_permissions`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/host_permissions) in the `manifest.json` file. That's a requirement of the WebExtension API and adds to security. In my understanding, there's no way to retroactively allow an add-on to make requests to hosts that were not specified in the manifest. The whole discussion in https://github.com/muety/wakapi/issues/237 is around just that. Please correct me if I'm wrong.

**Comment by SettingDust** [comment]
https://github.com/SettingDust/obsidian-web-clipper/blob/main/src/app/options/general/general.component.ts#L46-L52

Can grant permission with this

**Comment by muety** [comment]
Very cool, didn't know that! I filed an issue with the official plugin, see https://github.com/wakatime/browser-wakatime/issues/209. Maybe we can even get rid of [chrome-wakapi](https://github.com/muety/chrome-wakapi) in the long run.

**Comment by muety** [comment]
https://github.com/wakatime/browser-wakatime/pull/221
