### ISSUE TITLE
Different Summary Calculations then Wakatime

### ISSUE THREAD

**Issue by ethanleifer** [muety/wakapi#488]
Hi, 

I have been a long-time user of Wakatime but wanted control over my own data. 

I spun up my own instance of Wakapi backed by a Postgres database. 

I went an imported my Wakatime data into Wakapi. The summary coding time between both tools is drastically different. Why is that? 

I have wiped the database and restarted it a few times to confirm this wasn't an issue. 

I would appreciate any insight.

Here are some screenshots: 

<img width="1173" alt="Screen Shot 2023-05-18 at 11 01 15 PM" src="https://github.com/muety/wakapi/assets/17654498/0e6c9292-445f-4dd4-afe0-5c2c97e7730a">
<img width="387" alt="Screen Shot 2023-05-18 at 11 01 24 PM" src="https://github.com/muety/wakapi/assets/17654498/56aac4ad-3771-44e8-aa46-ae784896601e">

<img width="1172" alt="Screen Shot 2023-05-18 at 11 01 43 PM" src="https://github.com/muety/wakapi/assets/17654498/6926f0b0-81b9-48b7-b61c-6be30c23c9b9">
<img width="412" alt="Screen Shot 2023-05-18 at 11 01 49 PM" src="https://github.com/muety/wakapi/assets/17654498/23774fa1-8dd3-4225-8ccc-92b7c32c32bd">

**Comment by muety** [comment]
Hi @ethanleifer, thanks for using Wakapi! This question was raised a couple of times already. In fact, WakaTime and Wakapi will never show the same total time. This is due to the fact that they estimate that time differently, see our [FAQ ("_How are durations calculated?_")](https://github.com/muety/wakapi#-faqs). Unfortunately, there is no right or wrong here and we can't know for sure precisely what the actual, true coding time was, only judging by heartbeats. Calculations are just heuristic, so there will always be a discrepancy.

**Comment by ethanleifer** [comment]
Thanks for the information. That makes sense!

**Comment by ethanleifer** [comment]
Is there a way to make the two calculations line up?

**Comment by muety** [comment]
#156 could help in that regard.
