### ISSUE TITLE
Using a password longer than 72 characters results in an error

### ISSUE THREAD

**Issue by Daste745** [muety/wakapi#494]
**Describe the bug**
When trying to register an account or change Your password to anything over 72 characters, a "Failed to create new user" error banner appears.

Server logs:
```
[ERROR] failed to create new user - bcrypt: password length exceeds 72 bytes
[INFO ] [request] status=500, method=POST, uri=/signup, duration=5.879177ms, bytes=6164, addr=10.0.0.2, user=-
```

**System information**
* Wakapi version - 2.7.0
* Operating system
    * Docker - ghcr.io/muety/wakapi:latest (on arm64)
* Database - Postgres 14.2

**Comment by muety** [comment]
Thanks for bringing this up! Seems to be a limitation of bcrypt. I might look into changing the hash algorithm to argon2id as [recommended by OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html) or something else. Low prio, though, because 72 chars are generally way enough.
