### ISSUE TITLE
Badge labels cached improperly

### ISSUE THREAD

**Issue by Skillkiller** [muety/wakapi#496]
**Describe the bug**
Hello,
I noticed that with the Badge API the labels are not taken into account during caching. This has the consequence that a label change in the request is not considered in the response accordingly. This is caching problem and I assume it has to do with [this](https://github.com/muety/wakapi/blob/c9f2518fbcdf30616404345353650d4829f5aac5/routes/api/badge.go#L54) line. As it looks, the label is not included in the cache key.

Assumption: Caching is enabled on the server.
Example of the problem:
1. GET ``https://wakapi.dev/api/badge/n1try/interval:any/project:cache?label=Label1``
Response:
![grafik](https://github.com/muety/wakapi/assets/18444809/6add0c93-652e-4eb3-98be-cc1041d4b8d0)
The answer has the label ``Label1`` accordingly in the badge.
2. GET ``https://wakapi.dev/api/badge/n1try/interval:any/project:cache?label=OtherLabel``
Response:
![grafik](https://github.com/muety/wakapi/assets/18444809/65c468aa-5add-4d1a-b838-5a8be252095f)
This response does not contain the requested label ``OtherLabel`` but the old label ``Label1`` from the previous request.

**System information**
Please provide information on:
* Wakapi version: 2.7.0
* Operating system
    * If Linux: which distro?
    * If Docker: ghcr.io/muety/wakapi:2
* Database MySQL

**Comment by muety** [comment]
Good find! Actually, it's not a caching problem. The filters are respected by the cache key (see the `filters.Hash()` part). The problem is a different one. 

Passing `label` as a query parameter is syntactically not correct. For compatibility with the Shields.io (see [this endpoint](https://wakapi.dev/swagger-ui/swagger-ui/index.html#/badges/get-badge)), filters are instead accepted as path parameters (e.g. `project:cache`). However, only one such entity filter is currently supported at a time. 

I might want to look into extending this to allowing additional filters, e.g. in a format like `project:blaah,label:foo`. At least for the Shields.io-compatible endpoint. For our own `/badges` endpoint (that is not constrained by any upstream requirements), we could actually change the format entirely and properly make use of query params the way you would intuitively expect it (e.g. `?project=blahh&label=foo`), see [here](https://github.com/muety/wakapi/blob/1a6ee55d144574ef890d3de2825a9adac69a818e/helpers/summary.go#L47-74). The only reason why I'm a bit reluctant about this is the fact that it would be a breaking change for anybody using this endpoint productively.

**Comment by Skillkiller** [comment]
I think there is a misunderstanding. We are talking about two different things. You are talking about the filter options which also includes a label filter. /compat/shields/v1/{user}/{interval}/**{filter}**.

I am talking about the badge label that is displayed and not the filter. /compat/shields/v1/{user}/{interval}/{filter}**?label=123**.
I would like to point out that the returned badge does not always show the passed label. Here is some more information about my previous example:
2. GET ``https://wakapi.dev/api/badge/n1try/interval:any/project:cache?label=OtherLabel``
Response:
![grafik](https://github.com/muety/wakapi/assets/18444809/65c468aa-5add-4d1a-b838-5a8be252095f)
This response does not contain the requested label ``OtherLabel`` but the old label ``Label1`` from the previous request.  
Expected Response: 
![Unbenannt](https://github.com/muety/wakapi/assets/18444809/6345c85b-683d-4584-9a46-dea647647278)
