### ISSUE TITLE
OS and Editor not compatible with wakatime-mode (emacs)

### ISSUE THREAD

**Issue by notarock** [muety/wakapi#53]
Hey there! I just installed this on my server and I'm pretty happy with it so far. But I think there might be an issue on my end or with the `user_agent` parameter...

![image](https://user-images.githubusercontent.com/25652765/94515789-60a3e800-01f2-11eb-8bb2-f049edeb39cd.png)

![image](https://user-images.githubusercontent.com/25652765/94515900-a2cd2980-01f2-11eb-97c0-2db653a3dfb8.png)

When I am using Emacs to edit files, the server doesn't seem to pickup the editor I am using and simply leave the field as blank...
Ignore the "emacs" entry in the pie chart, I actually edited that by hand inside the database.

I have investigated the issue and found out that the `user_agent` parameter is used to find out what OS / Editor were used.
I saw that through looking at `./scripts/push_sample_data.py` and `./routes/heartbeat.go` which lead me to `ParseUserAgent`. I tried looking through my `wakatime.log` file and found this:

`'user_agent': 'wakatime/13.0.4 (Linux-5.4.64-x86_64-with-glibc2.2.5) Python3.7.6.final.0 emacs-wakatime/1.0.2'`

For more context, I am currently using Nixos. I have tried the same setup inside of Ubuntu and I can recreate the issue no problem, so it seems to be a bug with the emacs-mode plugin, which seems to work fine with the wakatime website (Not tested so im not sure)  

When I use the wakatime CLI directly from the terminal, the OS get picked up (With `Unknown` as the editor ofc), so I think it's caused by wakatime-mode.el ...

**Comment by muety** [comment]
Thanks a lot for bringing this up and for the hints you already gave me! I investigated the problem briefly and found that it's simply a issue with the regex that parses the user agent string. I came up with this regex by myself and it's not very robust yet, as I only tested it with the user agent string from three different editor-/OS-combinations.

Take a look at the following. [This](https://regex101.com/r/xO4OSQ/1) regex is the current, faulty one. It works for the second user agent (Ubuntu + GoLand), but not for the first one (Nixos + emacs) due to a trivial bug. [This fixed one](https://regex101.com/r/h1Vp3T/1), however, works. 

I'm going to push a fix to `master` later this day.
