### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by Guray00** [muety/wakapi#583]
I installed wakapi with the auto installer from the command line, which is the best way to correctly upgrade to the new version without losing data?

**Comment by muety** [comment]
Hi @Guray00, you can simply run the same script again. It will always pull the latest version and overwrite the `wakapi` executable as well as the `config.yml` in your current directory, if existing. So make sure to backup your config file before running the command (e.g. rename it to `config.custom.yml`, then run the script, then delete `config.yml` and then rename your own config back to its original name). There's no risk of losing data, because the script won't touch your SQLite database. Hope that helps!

**Comment by Guray00** [comment]
Thank you! I wasn't sure about that. Is it possible to add it to the FAQ?
