### ISSUE TITLE
[Feature request] Support SQL Server as database

### ISSUE THREAD

**Issue by ddadaal** [muety/wakapi#591]
It would be great if wakapi can support SQL Server as the database. [gorm does support sql server](https://gorm.io/docs/connecting_to_the_database.html#SQL-Server), so it shouldn't be so hard to support it. I am already working on it [here](https://github.com/ddadaal/wakapi-sqlserver/tree/add-mssql-support).

Blockers:

-  SQL Server doesn't allow multiple columns in a table with `timestamp` type

Reason: [this stackoverflow question](https://stackoverflow.com/questions/12063850/multiple-timestamp-columns-in-sql-server-2000)

Workaround: Use [gorm's support for custom data type](https://gorm.io/docs/data_types.html#GormDataTypeInterface). Implemented `GormDBDataType` interface for `CustomTime`, use `datetimeoffset` for sqlserver dialector.

It adds a new optional `TIMESCALE` gorm tag, to set the scale (precision) of the `datetimeoffset` or `timestamp`. For example, `timeScale:3` yields `datetimeoffset(3)` for sql server, and `timestamp(3)` for other dialector.

- `./testing/run_api_tests.sh sqlserver --migration` cannot connect to db, but `./testing/run_api_tests.sh sqlserver` can.

Still investigation.

- `Could not create constraint or index. See previous errors.`

Still under investigation 

- `default:CURRENT_TIMESTAMP` might not be optimal for `doptimaloffset`

**Comment by muety** [comment]
Hi @ddadaal, thanks for requesting this feature! I didn't particularly plan to support more databases. On the contrary, there had even been short discussions in the past around _dropping_ support for either MySQL or Postgres or both.

While Gorm generally does a great job abstracting from the specific DBMS, we still run into SQLite- / Postgres- / MySQL-specific issues every now and then. You'll find quite a few places in the code where check for the specific database to run different pieces of code. Also, more complex queries, that can't be implemented through Gorm, but require raw SQL, are a bit painful to maintain when supporting multiple databases. For example, I once had a quite efficient pure-SQL implementation of the entire heartbeats aggregation logic. But it used MySQL-specific functions, so would have had to be duplicated and modified for SQLite and Postgres as well.

However, since we decided against dropping one of the databases for now and since you're already working on SQL Server support anyway, I'd say let's go for it! Your contribution will be very welcome! :raised_hands: 

Only a very minor, unimportant remark regarding your current code: could you use `mssql` instead of `sqlserver` to refer to SQL Server throughout the code?

**Comment by YC** [comment]
Hi @ddadaal, `--migration` will fail because the latest release of `wakapi` (prior to your implementation) -- which is download automatically won't support mssql. 
Please add `mssql` to the list in `ci.yml`, but there's no need to worry about CI failures relating to this.

**Comment by ddadaal** [comment]
Thanks @muety and @YC! 

I (might) have resolved most of the blockers I have encountered on the way. Currently, wakapi can be started with mssql. From what I see, `./run_api_tests.sh` doesn't run tests against dbs other than `sqlite`, does it? So now I have to manually run the project and test these functionalities to see if everything is working correctly.

Honestly, it is more complicated than I originally anticipated: there are lots of things that were taken granted for in other dbs, but are not valid in mssql. Here is an incomplete list:

- no `TRUE` or `FALSE` literals in mssql. Use `1` and `0` instead
- cannot give an alias to the table when `update`: in `update table as t set xxx = xxx`, `as t` is invalid
- mssql are strict about cascade paths on foreign keys (see [this stackoverflow answer](https://stackoverflow.com/a/852047))

It is a big challenge to support multiple dbs, even with the help from gorm. gorm dialectors have solved most of the problems, and we should make good use of it. I've got a suggestion that we should provide gorm and go version of all db operations that act as the last resort and add raw SQLs for specific dbs in specific scenarios when optimization is needed. We should also provide tests that initialize data and check results using gorm so that we can test against all dbs using one set of code.

**Comment by ddadaal** [comment]
I've submitted a PR for this. 

Actually most of SQL changes are pretty trivial, most about quoting identifiers and removing/replacing unsupported features. It should not impact the code too much.

I will try running the mssql version for longer time and see the result.
