### ISSUE TITLE
Add Support for Regex in Settings#Data

### ISSUE THREAD

**Issue by ysxninja** [muety/wakapi#607]
In Settings#Data Aliases:
Add the ability to specify aliases for any type of entity as regex. 
For instance, to be able to define a rule, that all occurrences of ```.*\bmyapp\b.*``` e.g. ```myapp-frontend```, ```myapp-dev```, ```myapp-yetknownfuture``` are combined under a project called ```myapp.```

**Comment by muety** [comment]
Had some thoughts about this again. I have a fear that allowing arbitrary regexes from user input might become a security risk, e.g. because of the problem of [catastrophic backtracking](https://www.regular-expressions.info/catastrophic.html) or potential regex injections.

I'm thinking about implementing `glob`-like wildcard patterns instead (e.g. `app-*`). This would be less powerful, but might still suffice for your use cases, @ysxninja @gingerbeardman?

**Comment by gingerbeardman** [comment]
Sure thing! I'll probably only use * anyway 😬
