### ISSUE TITLE
category unknown

### ISSUE THREAD

**Issue by onns** [muety/wakapi#642]
**Describe the bug**
A clear and concise description of what the bug is. Please briefly describe how to reproduce the bug as well as _expected_ vs. _actual_ behavior. Optionally include screenshots and server logs, if helpful.

the latest version, sqlite, linux

![image](https://github.com/muety/wakapi/assets/16622934/b4d80dd4-5a7d-4c56-825f-80c34b14300a)

what should I do to fix this? It should be "browsing". I check the heartbeat and the category value is empty, but the wakatime-cli is the latest version.
![image](https://github.com/muety/wakapi/assets/16622934/e79cd638-5de3-40b3-a043-2df40cab6a12)

**Comment by muety** [comment]
Hi @onns, for web browing, the [browser-wakatime](https://github.com/wakatime/browser-wakatime) extension is responsible, rather than the wakatime-cli. It doesn't specify a category for heartbeats, but that's nothing we could change on Wakapi's end. If you want the browser plugin to support categories (usually you'd use them for thing like "coding", "testing", "code review", ...), please file an issue with them.
