### ISSUE TITLE
way to set weekly report duration 

### ISSUE THREAD

**Issue by onns** [muety/wakapi#645]
Strictly speaking, weekly report should be like [from,to), include the start and not include the end.

If I receive email at 18:00, the day range is 8 days, which is confusing. Setting the send email time to 00:00:00 does not solve this.

So I wonder if I could set the duration from Monday 00:00:00 to Sunday 23:59:59, or next Monday 00:00:00 but exclude the 00:00:00?

**Comment by muety** [comment]
Hi @onns, I think it's sensible to include the day at which the report is sent. When I receive my report Friday afternoon, I'd want to use it to recap my past work week. Currently, the report covers precisely 7 days, which is, e.g., from last Friday 6 pm to "today's" Friday 6 pm. However, I see how this lead to confusion, because the report only says "Friday", but doesn't clearly indicate that it's actually _"Friday >= 6 pm"_. We might want to clarify this in the e-mail.

**Comment by muety** [comment]
What do you think?
