### ISSUE TITLE
User agent string from desktop-wakatime parsed improperly

### ISSUE THREAD

**Issue by Bashev** [muety/wakapi#686]
From few months wakatime has desktop app (https://github.com/wakatime/desktop-wakatime) and it seems to works with wakapi, but ... data comes with some deviations in editors section. 

Desktop App partially covered support of different apps which can be tracked and is useful workaround if your tool is not supported natively yet.

Wakapi
![image](https://github.com/user-attachments/assets/87e2abdc-a3ab-4c14-b356-240d174e4b97)

Wakatime
![image](https://github.com/user-attachments/assets/43bab3f6-e110-4f4c-a015-7e6cf4a0edda)

Is it a data "mapping" issue or something changed on the wakatime side? Can this be applied to wakapi?

**Comment by muety** [comment]
Didn't know about the desktop app, very interesting. Thanks for reporting this! I'll have an in-depth look soon and keep you posted.

**Comment by muety** [comment]
Unfortunately, I can't currently use the app due to https://github.com/wakatime/desktop-wakatime/issues/44. However, I dug through the code a bit and gathered a couple of hints.

Plugin user agent string is constructed in [wakatime.ts#L244](https://github.com/wakatime/desktop-wakatime/blob/main/electron/watchers/wakatime.ts#L244) with the `versionString` part being something like `windows-wakatime/1.2.3`. The user agent string then perhaps becomes something like `<appName>/1.2.3 windows-wakatime/1.2.3`. Wakapi uses the regex in [http.go#L88](https://github.com/muety/wakapi/blob/ef2776f2cd988d14a6516321a375ff93d315f534/utils/http.go#L88) to parse that user agent string and default UA parsing as a fallback.´

Most probably, the issue lies somewhere in how we parse the user agent strings. To debug this further, however, I'd have to know exactly how the plugin constructs them and see some examples. 

@Bashev, are you on Wakapi.dev? If yes, could you share your user name, please? If you're self-hosting instead, could you do me a favor and send some exemplary rows from your database's `heartbeats` table, that correspond to heartbeats sent by the desktop app?

**Comment by Bashev** [comment]
CSV [wakapi-desktop-extracted-heartbeats.csv](https://github.com/user-attachments/files/17368569/wakapi-desktop-extracted-heartbeats.csv) or SQL [wakapi-desktop-extracted-heartbeats.zip](https://github.com/user-attachments/files/17368593/wakapi-desktop-extracted-heartbeats.zip)

Looks like Editor is not recognized or overridden by 'Windows' for example: 
- debugging apps is Postman
- meeting app is Zoom (but Skype or Microsoft Teams are not recognized to meeting)

**Comment by muety** [comment]
Resolved in 699dab8b2768f055e59a40d93c4c0ab31ce70e16.
