### ISSUE TITLE
Incorrect Title for Embedded GitHub Status Card

### ISSUE THREAD

**Issue by WilliamZheng27** [muety/wakapi#715]
**Describe the bug**
The number of hours shown by embedded GitHub status cards doesn't seem right (way too long for a single week). After checking the original program, it seems like it is actually **Yearly** summary, not weekly.
![image](https://github.com/user-attachments/assets/51228ff5-402b-4f69-8929-74089322d260)
![image](https://github.com/user-attachments/assets/b4e72baa-4499-4f0e-a997-a4865a9a2908)
Ref: https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#wakatime-stats-card

**System information**
Using [wakapi.dev](https://wakapi.dev/)
* Wakapi version: v2.12.2-946985e
* Operating system: Linux
* Database: MySQL

**Comment by muety** [comment]
Thanks for pointing that out! You can simply change the title by changing the `custom_title` URL query parameter. But I'll also fix the preset for consistency.

General question: do you think yearly or weekly stats would be preferable for the stats card? I actually tend to prefer _weekly_ stats, because [my yearly card](https://github-readme-stats.vercel.app/api/wakatime?username=n1try&api_domain=wakapi.dev&bg_color=1A202C&title_color=2F855A&icon_color=2F855A&text_color=ffffff&custom_title=Wakapi%20Week%20Stats&layout=compact) is insanely large and doesn't really look good in a README.

**Comment by WilliamZheng27** [comment]
> Thanks for pointing that out! You can simply change the title by changing the `custom_title` URL query parameter. But I'll also fix the preset for consistency.
> 
> General question: do you think yearly or weekly stats would be preferable for the stats card? I actually tend to prefer _weekly_ stats, because [my yearly card](https://github-readme-stats.vercel.app/api/wakatime?username=n1try&api_domain=wakapi.dev&bg_color=1A202C&title_color=2F855A&icon_color=2F855A&text_color=ffffff&custom_title=Wakapi%20Week%20Stats&layout=compact) is insanely large and doesn't really look good in a README.

I agree weekly status will make more sense for most use cases, but is it possible to make it configurable for users? e.g. weekly, monthly, quarterly or custom time range.

**Comment by muety** [comment]
Alright, had a look at this again. There was a related issue, #508, which was our reaction to _github-readme-stats_ removing support for the `range` parameter, see https://github.com/anuraghazra/github-readme-stats/pull/2707. Since then, the card will always display whatever time range you set under _Settings -> Permissions -> Time Range_. If you set it to -1, the card will display _all_ your coding time stored in Wakapi (which is why mine is so huge). 

The card display whatever the `/stats` endpoint returns, which, in turn, will output whatever you configured as the permitted time range. My preference would be to add support for `?range` back into the readme _github-readme-stats_ again. Otherwise, the only way to configure your card's time range is via Wakapi's settings, unfortunately.

Apart from that, the card title is still display wrong, regardless of the above discussion. I'll fix that soon! 

<details>
<summary>Implementation notes to myself</summary>
By default, the card's title will be set according to [here](https://github.com/anuraghazra/github-readme-stats/blob/3b2c8885fc27574ad1880932ad961548f7c2db4b/src/cards/wakatime-card.js#L382), unless overridden by the optional `custom_title`. Default title will be different for whatever `range` is returned by the stats endpoint, however, only `last_7_days`, `last_year` are supported besides the default generic title.

👉 There's no way for Wakapi to fully customize the title (e.g. to "All time"), unless the user passes a `custom_title` for their card. 

👉 Simply remove the `custom_title` attribute from the URL preset to at least avoid confusion.
</summary>

**Comment by muety** [comment]
Fixed the `custom_title` parameter in the URL preset that is shown on the settings page.

Unfortunately, since there's no reply on the upstream issue (regarding `range` param), the only way to customize your card's time range remains through adapting your _Public Data Time Range_ under _Settings_.
